site_name: Swiftcord Documentation
site_url: https://sketchmaster2001.github.io/Swiftcord-Docs/
site_author: Swiftcord Community
site_description: Swiftcord documentation (API library for discord written in Swift).

# Repository
repo_name: Swiftcord Github
repo_url: https://github.com/SketchMaster2001/Swiftcord

# Navigation
nav:
  - Home: index.md
  - About: about.md
  - Getting Started:
    - New Project: getting-started/new-project.md
    - Connect the bot: getting-started/connect-to-discord.md
  - Basics:
    - Slash Commands: basics/slash-commands.md
    - Buttons: basics/buttons.md
    - Select Menus: basics/select-menu.md

# Configuration
theme:
  language: en
  name: material
  logo: assets/logo2.png
  favicon: assets/favicon.ico
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
      primary: deep orange
      accent: amber

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
      primary: deep orange
      accent: amber
  features:
    - navigation.top
    - search.suggest
    - search.highlight

# Socials
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/cE2Cpn4r9X
    - icon: fontawesome/brands/github
      link: https://github.com/SketchMaster2001/Swiftcord

# Copyright
copyright: Copyright &copy; Swiftcord community

# Extensions
markdown_extensions:
  # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#supported-types
  - admonition
  - meta
  - toc:
      permalink: true

extra_javascript:
  - javascripts/syntax.js

extra_css:
  - stylesheets/syntax.css
    